### ISSUE TITLE
destroy is not a function 

### ISSUE THREAD

**Issue by abhishek-fareye** [alex3165/react-leaflet-draw#98] opened 2021-04-06 09:34 UTC
![image](https://user-images.githubusercontent.com/47735030/113690356-ef854600-96e8-11eb-9d49-364b1c194a45.png)
getting this error 
while inspecting react-leaflet-draw@0.19.7
useEffect code is using return null
![image](https://user-images.githubusercontent.com/47735030/113690641-43902a80-96e9-11eb-8f90-e65e22d3e213.png)
return can notbe anything other than a function
![image](https://user-images.githubusercontent.com/47735030/113690768-60c4f900-96e9-11eb-839d-5734c576b907.png)

**Comment by DVGY** [comment] 2021-04-16 18:06
@abhishek-fareye can you put an example repo or share your GitHub I want to learn why is this causing an error.

**Comment by tsotnetest** [comment] 2021-04-22 14:29
I have same problem

**Comment by nikilopes** [comment] 2021-04-26 20:15
same problem

**Comment by patrickgodinho** [comment] 2021-05-14 19:15
Same error here, have you guys fixed it?

**Comment by Beft9** [comment] 2021-06-08 14:05
Actually it comes up because of rendering draw feature group more than once. It correctly runs, when rendering it in last state change. But i dont know how can i solve it permanently. Any time i want to change state on interface it happens again

**Comment by premdav** [comment] 2021-06-17 15:54
We are running into this same issue. It is happening any time we try rendering the EditControl. Does anyone have a fix for this yet?

**Comment by DVGY** [comment] 2021-06-17 15:59
> We are running into this same issue. It is happening any time we try rendering the EditControl. Does anyone have a fix for this yet?

@premdav  can you provide standalone example please ?

**Comment by premdav** [comment] 2021-06-17 16:07
> > We are running into this same issue. It is happening any time we try rendering the EditControl. Does anyone have a fix for this yet?
> 
> @premdav can you provide standalone example please ?

This is the component we are using to attempt rendering the map and edit controls. When we comment out the <EditControl /> component, we are getting the error shown below. 

```typescript
import React, { useState, useRef } from "react";
import {
  MapContainer,
  TileLayer,
  Marker,
  FeatureGroup,
  Circle,
} from "react-leaflet";
import { EditControl } from "react-leaflet-draw";
import "leaflet/dist/leaflet.css";
import "leaflet-draw/dist/leaflet.draw.css";
const SenderMap = (): JSX.Element => {
  const [center, setCenter] = useState({ lat: 37.271, lng: -79.9414 });
  const zoomValue: number = 9;
  const _onCreate = (e: any) => {
    console.log(e);
  };
  const _onEdit = (e: any) => {
    console.log(e);
  };
  const _onDelete = (e: any) => {
    console.log(e);
  };
  return (
    <MapContainer
      className="map_container"
      center={center}
      zoom={zoomValue}
      scrollWheelZoom={true}
      style={{ height: "50vh" }}
      zoomControl={true}
    >
      <TileLayer
        attribution='&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
        url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
      />
      <FeatureGroup>
        <EditControl
          position="topright"
          onCreated={_onCreate}
          onEdited={_onEdit}
          onDeleted={_onDelete}
          draw={{
            rectangle: true,
            polyline: true,
            circle: false,
            circlemarker: false,
            marker: false,
          }}
        />
      </FeatureGroup>
    </MapContainer>
  );
};
export default SenderMap;
```

![image (2)](https://user-images.githubusercontent.com/35507470/122433731-1a4b1080-cf5c-11eb-9bc5-79cf8df39847.png)

**Comment by DVGY** [comment] 2021-06-17 16:09
> When we comment out the component

@can you provide a codesandbox. It kinda hard to run this please.

**Comment by acepitcher2009** [comment] 2021-06-17 16:12
> > When we comment out the component
> 
> can you provide a codesandbox. It kinda hard to run this please.

when we comment out the editcontrol component the map will render but we get the error above other wise

**Comment by DVGY** [comment] 2021-06-17 16:26
> > > When we comment out the component
> > 
> > 
> > can you provide a codesandbox. It kinda hard to run this please.
> 
> when we comment out the editcontrol component the map will render but we get the error above other wise

@acepitcher2009 @premdav It seems to working fine in my case. I am using  "react-leaflet": "^3.0.0",  "react-leaflet-draw": "^0.19.8",. Can you pls provide a standalone example for this on codesanbox?
 Maybe my code is too simple that why it cannot reproduce

**Comment by premdav** [comment] 2021-06-17 16:28
@DVGY I think the issue may have been with the react version we were using. We updated to the new 17.0.2 from 16.13.1 and everything started working all of a sudden. Not sure what was going on but it is all working now. Thank you for your promptness.

**Comment by DVGY** [comment] 2021-06-17 16:29
> @DVGY I think the issue may have been with the react version we were using. We updated to the new 17.0.2 from 16.13.1 and everything started working all of a sudden. Not sure what was going on but it is all working now. Thank you for your promptness.

  "react": "^17.0.1",
    "react-dom": "^17.0.1", even i am using this version. Thanks

**Comment by mariohmol** [comment] 2021-08-06 20:05
thanks @premdav 

I can confirm this!

Before after a change on the state I got the error.. after using react 17 its gone!! thanks a lot

**Comment by brenonovelli** [comment] 2022-05-11 13:32
Eu copiei todo EditControl, fiz um componente local, removi os `return false` e `return null` do segundo useEffect e voltou a funcionar. Vou testar por uns dias para ver se fica tudo ok.

<img width="375" alt="image" src="https://user-images.githubusercontent.com/3636449/167862063-bd0484d5-4b7a-49f8-a9ce-c6ec9a532aab.png">

**Comment by brennanwilkes** [comment] 2022-06-23 20:46
[Version 0.20.0](https://www.npmjs.com/package/react-leaflet-draw/v/0.20.0) patches this issue. Please let me know if there are any bugs or issues with it

**Closed by brennanwilkes** 2022-06-23 20:46 UTC
