### ISSUE TITLE
react-leaflet v4 and React v18 (not supporting)

### ISSUE THREAD

**Issue by YummyTi** [alex3165/react-leaflet-draw#144] opened 2022-05-24 06:39 UTC
Please support for react-leaflet v4 and react version 18

**Comment by MLNW** [comment] 2022-05-30 06:50
Duplicate of #139

**Comment by hoangdangcodecomplete** [comment] 2022-05-31 03:01
@MLNW Can I select one of many polygons to change color or show a popup on the polygon I choose?
I wanna choose one of many polygons or polylines to change the color or add the popup of that shape after I finished drawing.
![Screen Shot 2022-05-31 at 09 54 05](https://user-images.githubusercontent.com/104552361/171084210-e0dba863-3ee4-48ac-a67f-568398b61b92.png)

**Closed** 2022-06-23 19:57 UTC

**Comment by brennanwilkes** [comment] 2022-06-23 20:13
@YummyTi  [Version 0.20.0](https://www.npmjs.com/package/react-leaflet-draw/v/0.20.0) patches this issue. Please let me know if there are any bugs or issues with it
